### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by leopqrz** [IS2AI/SpeakingFaces#1]
This is probably the best dataset with thermal and visual images I have ever seen. Thank you very much for that work. 

I've filled the form, received confirmation from google forms but did not receive any credentials or instructions on how to connect to your server and download the dataset. 

Thank you,

Leonardo Queiroz
University of Calgary

**Comment by akuzdeuov** [comment]
Dear Leonardo, 

Thank you for your interest in our dataset. We will send you credentials as soon as possible. 

Kind regards,
Askat
