### ISSUE TITLE
Thermal data

### ISSUE THREAD

**Issue by leopqrz** [IS2AI/SpeakingFaces#2]
Dear authors,

I am wondering if you have the thermal data related to the thermal image, which would correspond with the temperature of each pixel and not only the RGB colours. Thanks in advance.

Best,

Leonardo Queiroz

**Comment by abdrakh1** [comment]
Dear Leonardo, 

We did not collect temperature values. We only captured thermal images, where the hottest object in an image will have the lightest color regardless of what the actual heat of the object is. 

As the result, we cannot provide the thermal data, as we don't have them, or any tool to convert images to temperature matrices.

Best wishes,
Madina
