### ISSUE TITLE
Usage license policy 

### ISSUE THREAD

**Issue by leopqrz** [IS2AI/SpeakingFaces#3]
Are there any restrictions on using your dataset to recreate a new dataset based on it?
Where can I find the usage license policy?

**Comment by abdrakh1** [comment]
Dear Leonardo,

SpeakingFaces is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). 

You can use our dataset for these purposes, as long as your credit our work by citing [our paper](https://arxiv.org/abs/2012.02961) and asking your potential users to cite it as well, in addition to your work.

Best,
Madina
