### ISSUE TITLE
FLIR ATLAS record datas

### ISSUE THREAD

**Issue by GCaptainNemo** [IS2AI/SpeakingFaces#4]
Can FLIR ATLAS SDK be used in ubuntu？

**Comment by akuzdeuov** [comment]
Support for Linux-based Operating Systems is limited. Thus, we recommend using Windows OS.

**Comment by GCaptainNemo** [comment]
> Support for Linux-based Operating Systems is limited. Thus, we recommend using Windows OS.

Thank you for your answer！
